const WORKOUT_DATA = {
    0: { // 등
        day: '등',
        type: '등 운동',
        emoji: '🏋️',
        exercises: [
            { name: '랫 풀다운', detail: '광배근 상부', emoji: '🏋️' },
            { name: '바벨 로우', detail: '등 전체 두께', emoji: '💪' },
            { name: '데드리프트', detail: '후면 사슬 전체', emoji: '🔥' },
            { name: '풀업', detail: '광배근 발달', emoji: '💪' },
            { name: '시티드 로우', detail: '등 중앙부', emoji: '🏋️' },
            { name: '원암 덤벨 로우', detail: '광배근 고립', emoji: '🔥' },
            { name: '티바 로우', detail: '등 하부 두께', emoji: '🎯' },
            { name: '케이블 암 풀다운', detail: '광배근 하부 고립', emoji: '🎯' },
            { name: '벤트 오버 바벨 로우', detail: '등 상부', emoji: '💪' },
            { name: '인버티드 로우', detail: '등 근력 강화', emoji: '🔥' },
            { name: '페이스 풀', detail: '후면 삼각근 및 승모근', emoji: '⭐' },
            { name: '슈러그', detail: '상부 승모근', emoji: '🏋️' },
            { name: '백 익스텐션', detail: '척추기립근', emoji: '🔥' },
            { name: '클로즈 그립 랫 풀다운', detail: '광배근 안쪽', emoji: '🎯' },
            { name: '언더그립 랫 풀다운', detail: '광배근 하부 및 이두', emoji: '💪' },
            { name: '루마니안 데드리프트', detail: '등 하부 및 햄스트링', emoji: '🔥' },
            { name: '랙 풀', detail: '등 상부 및 기립근', emoji: '🏋️' },
            { name: '머신 로우', detail: '안정적인 등 운동', emoji: '🎯' },
            { name: '풀오버', detail: '광배근 및 가슴 확장', emoji: '⭐' },
            { name: '친업', detail: '등 및 이두 강화', emoji: '💪' }
        ]
    },
    1: { // 가슴
        day: '가슴',
        type: '가슴 운동',
        emoji: '💪',
        exercises: [
            { name: '벤치프레스', detail: '가슴 전체', emoji: '🏋️' },
            { name: '인클라인 벤치프레스', detail: '상부 가슴', emoji: '🔥' },
            { name: '덤벨 벤치프레스', detail: '가동범위 극대화', emoji: '💪' },
            { name: '딥스', detail: '하부 가슴', emoji: '🔥' },
            { name: '덤벨 플라이', detail: '가슴 안쪽 고립', emoji: '⭐' },
            { name: '푸시업', detail: '맨몸 가슴 운동', emoji: '💪' },
            { name: '체스트 프레스 머신', detail: '안정적인 가슴 운동', emoji: '🎯' },
            { name: '인클라인 덤벨 프레스', detail: '상부 가슴 집중', emoji: '🔥' },
            { name: '케이블 크로스오버', detail: '가슴 하부 및 안쪽', emoji: '🎯' },
            { name: '펙 덱 플라이', detail: '가슴 중앙 고립', emoji: '⭐' },
            { name: '디클라인 벤치프레스', detail: '하부 가슴 발달', emoji: '🏋️' },
            { name: '스미스 머신 벤치프레스', detail: '안전한 중량 운동', emoji: '🎯' },
            { name: '랜드마인 프레스', detail: '상부 가슴 및 어깨', emoji: '🔥' },
            { name: '클로즈 그립 벤치프레스', detail: '가슴 안쪽 및 삼두', emoji: '💪' },
            { name: '덤벨 풀오버', detail: '가슴 확장', emoji: '⭐' },
            { name: '머신 인클라인 프레스', detail: '상부 가슴 고립', emoji: '🎯' },
            { name: '와이드 푸시업', detail: '가슴 외측', emoji: '💪' },
            { name: '다이아몬드 푸시업', detail: '가슴 안쪽 및 삼두', emoji: '🔥' },
            { name: '플레이트 프레스', detail: '가슴 중앙 수축', emoji: '🎯' },
            { name: '디클라인 덤벨 프레스', detail: '하부 가슴 집중', emoji: '🏋️' }
        ]
    },
    2: { // 휴식
        day: '휴식',
        type: '휴식 및 스트레칭',
        emoji: '😴',
        exercises: [
            { name: '전신 스트레칭', detail: '근육 이완', emoji: '🧘' },
            { name: '폼롤러 마사지', detail: '근막 이완', emoji: '🌀' },
            { name: '가벼운 산책', detail: '회복 촉진', emoji: '🚶' },
            { name: '요가', detail: '유연성 향상', emoji: '🧘' }
        ]
    },
    3: { // 팔
        day: '팔',
        type: '팔 운동 (이두/삼두)',
        emoji: '🦾',
        exercises: [
            { name: '바벨 컬', detail: '이두 전체', emoji: '🏋️' },
            { name: '덤벨 컬', detail: '이두 고립', emoji: '💪' },
            { name: '케이블 푸시다운', detail: '삼두 전체', emoji: '🎯' },
            { name: '스컬 크러셔', detail: '삼두 매스 증대', emoji: '🔥' },
            { name: '해머 컬', detail: '상완근 및 전완근', emoji: '💪' },
            { name: '오버헤드 덤벨 익스텐션', detail: '삼두 장두', emoji: '🎯' },
            { name: '컨센트레이션 컬', detail: '이두 피크 발달', emoji: '🔥' },
            { name: '덤벨 킥백', detail: '삼두 외측두', emoji: '⭐' },
            { name: '프리쳐 컬', detail: '이두 하부 고립', emoji: '🎯' },
            { name: '로프 푸시다운', detail: '삼두 외측 수축', emoji: '💪' },
            { name: '클로즈 그립 벤치프레스', detail: '삼두 중량 운동', emoji: '🏋️' },
            { name: '인클라인 덤벨 컬', detail: '이두 장두 스트레칭', emoji: '🔥' },
            { name: '리버스 컬', detail: '전완근 강화', emoji: '💪' },
            { name: '벤치 딥스', detail: '삼두 맨몸 운동', emoji: '🔥' },
            { name: '21 컬', detail: '이두 펌핑 극대화', emoji: '⭐' },
            { name: '케이블 컬', detail: '지속적인 저항', emoji: '🎯' },
            { name: '원암 케이블 익스텐션', detail: '삼두 개별 고립', emoji: '💪' },
            { name: '스파이더 컬', detail: '이두 단두 집중', emoji: '🔥' },
            { name: '손목 컬', detail: '전완근 안쪽', emoji: '🎯' },
            { name: '리버스 손목 컬', detail: '전완근 바깥쪽', emoji: '💪' }
        ]
    },
    4: { // 하체
        day: '하체',
        type: '하체 운동',
        emoji: '🦵',
        exercises: [
            { name: '바벨 스쿼트', detail: '하체 전체', emoji: '🏋️' },
            { name: '레그 프레스', detail: '대퇴사두 위주', emoji: '💪' },
            { name: '레그 익스텐션', detail: '대퇴사두 고립', emoji: '🎯' },
            { name: '레그 컬', detail: '햄스트링 고립', emoji: '🔥' },
            { name: '런지', detail: '하체 및 둔근', emoji: '💪' },
            { name: '덤벨 스쿼트', detail: '안정적인 스쿼트', emoji: '🔥' },
            { name: '스티프 레그 데드리프트', detail: '햄스트링 및 둔근', emoji: '🎯' },
            { name: '카프 레이즈', detail: '종아리 발달', emoji: '⭐' },
            { name: '힙 쓰러스트', detail: '둔근 최강 운동', emoji: '🍑' },
            { name: '불가리안 스플릿 스쿼트', detail: '한쪽 다리 집중', emoji: '🔥' },
            { name: '핵 스쿼트', detail: '대퇴사두 중량', emoji: '🏋️' },
            { name: '이너 타이 머신', detail: '내전근 강화', emoji: '🎯' },
            { name: '아우터 타이 머신', detail: '중둔근 강화', emoji: '🍑' },
            { name: '고블렛 스쿼트', detail: '코어 및 하체', emoji: '💪' },
            { name: '스텝 업', detail: '하체 및 균형감각', emoji: '🔥' },
            { name: '글루트 햄 레이즈', detail: '후면 사슬 강화', emoji: '⭐' },
            { name: '워킹 런지', detail: '하체 지구력', emoji: '🏃' },
            { name: '스모 스쿼트', detail: '내전근 및 둔근', emoji: '🏋️' },
            { name: '박스 점프', detail: '하체 순발력', emoji: '🔥' },
            { name: '싱글 레그 프레스', detail: '불균형 교정', emoji: '🎯' }
        ]
    },
    5: { // 전신상체
        day: '전신상체',
        type: '상체 종합 운동',
        emoji: '🔥',
        exercises: [
            { name: '밀리터리 프레스', detail: '어깨 전체', emoji: '🏋️' },
            { name: '사이드 레터럴 레이즈', detail: '측면 어깨', emoji: '💪' },
            { name: '벤트 오버 레이즈', detail: '후면 어깨', emoji: '🔥' },
            { name: '아놀드 프레스', detail: '어깨 전면 및 측면', emoji: '⭐' },
            { name: '업라이트 로우', detail: '어깨 및 승모근', emoji: '🎯' },
            { name: '덤벨 숄더 프레스', detail: '어깨 중량 운동', emoji: '💪' },
            { name: '프론트 레이즈', detail: '전면 어깨 고립', emoji: '🔥' },
            { name: '페이스 풀', detail: '후면 어깨 및 등 상부', emoji: '🎯' },
            { name: '머신 숄더 프레스', detail: '안정적인 어깨 운동', emoji: '⭐' },
            { name: '케이블 레터럴 레이즈', detail: '지속적인 어깨 자극', emoji: '💪' },
            { name: '벤트 오버 덤벨 로우', detail: '등 상부', emoji: '🏋️' },
            { name: '인클라인 덤벨 프레스', detail: '상부 가슴', emoji: '🔥' },
            { name: '풀업', detail: '등 광배근', emoji: '💪' },
            { name: '딥스', detail: '가슴 하부 및 삼두', emoji: '🔥' },
            { name: '푸시업', detail: '가슴 및 코어', emoji: '🎯' },
            { name: '바벨 컬', detail: '이두', emoji: '💪' },
            { name: '스컬 크러셔', detail: '삼두', emoji: '🔥' },
            { name: '행잉 레그 레이즈', detail: '복근', emoji: '⭐' },
            { name: '플랭크', detail: '코어', emoji: '🧘' },
            { name: '버피 테스트', detail: '전신 유산소 근력', emoji: '🔥' }
        ]
    },
    6: { // 유산소
        day: '유산소',
        type: '유산소 및 복근',
        emoji: '🏃',
        exercises: [
            { name: '러닝머신', detail: '심폐지구력 향상', emoji: '🏃' },
            { name: '사이클', detail: '하체 부담 적은 유산소', emoji: '🚴' },
            { name: '천국의 계단', detail: '고강도 하체 유산소', emoji: '🪜' },
            { name: '일립티컬', detail: '전신 유산소', emoji: '🔄' },
            { name: '로잉 머신', detail: '전신 근지구력', emoji: '🚣' },
            { name: '줄넘기', detail: '순발력 및 유산소', emoji: '➰' },
            { name: '버피 테스트', detail: '고강도 전신 운동', emoji: '🔥' },
            { name: '마운틴 클라이머', detail: '코어 및 유산소', emoji: '⛰️' },
            { name: '점핑 잭', detail: '가벼운 유산소', emoji: '✨' },
            { name: '크런치', detail: '상복부 고립', emoji: '🔥' },
            { name: '레그 레이즈', detail: '하복부 고립', emoji: '💪' },
            { name: '플랭크', detail: '코어 안정성', emoji: '🧘' },
            { name: '러시안 트위스트', detail: '외복사근', emoji: '🎯' },
            { name: '바이시클 크런치', detail: '복근 전체', emoji: '🚴' },
            { name: 'V-업', detail: '상하복부 통합', emoji: '✌️' },
            { name: '할로우 바디 홀드', detail: '코어 강화', emoji: '⭐' },
            { name: '사이드 플랭크', detail: '측면 코어', emoji: '🧘' },
            { name: '데드 버그', detail: '코어 및 협응력', emoji: '🐞' },
            { name: '버드 독', detail: '코어 및 밸런스', emoji: '🐕' },
            { name: '플랭크 잭', detail: '코어 및 유산소', emoji: '🔥' }
        ]
    }
};
